# Generated by Django 5.1.3 on 2024-11-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog_post",
            name="author",
            field=models.CharField(default="Vivek..", max_length=100),
        ),
    ]
