# Generated by Django 5.1.3 on 2025-08-31 08:49

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_contact_form_alter_blog_post_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog_post",
            name="summry",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blog_post",
            name="desc",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
