# Generated by Django 5.1.3 on 2025-08-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_dasboard_page_delete_contact_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dasboard_page",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
